apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  labels:
    app: victoria-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
      - name: victoria-metrics
        image: victoriametrics/victoria-metrics:v1.112.0
        args:
          - '-storageDataPath=/victoria-metrics-data'
          - '-retentionPeriod=90d'
        ports:
          - containerPort: 8428